import ROOT
from ROOT import TFile, TCanvas, TLegend, TH1, TLine

fOldLoose = TFile.Open("20.1/Loose-noMll/histos.root")
fOldSignal = TFile.Open("20.1/Signal-noMll/histos.root")
fNewLoose = TFile.Open("loose/histos.root")
fNewSignal = TFile.Open("signal/histos.root")

hMassOldLoose = fOldLoose.Get("MassOS")
hMassOldLooseExp = fOldLoose.Get("MassExpSS")
hMassOldSignal = fOldSignal.Get("MassOS")
hMassOldSignalExp = fOldSignal.Get("MassExpSS")
hMassNewLoose = fNewLoose.Get("MassOS")
hMassNewLooseExp = fNewLoose.Get("MassExpSS")
hMassNewSignal = fNewSignal.Get("MassOS")
hMassNewSignalExp = fNewSignal.Get("MassExpSS")

hLeadingPtOldLoose = fOldLoose.Get("LeadingPtOS")
hLeadingPtOldLooseExp = fOldLoose.Get("LeadingPtExpSS")
hLeadingPtOldSignal = fOldSignal.Get("LeadingPtOS")
hLeadingPtOldSignalExp = fOldSignal.Get("LeadingPtExpSS")
hLeadingPtNewLoose = fNewLoose.Get("LeadingPtOS")
hLeadingPtNewLooseExp = fNewLoose.Get("LeadingPtExpSS")
hLeadingPtNewSignal = fNewSignal.Get("LeadingPtOS")
hLeadingPtNewSignalExp = fNewSignal.Get("LeadingPtExpSS")

hSubleadingPtOldLoose = fOldLoose.Get("SubleadingPtOS")
hSubleadingPtOldLooseExp = fOldLoose.Get("SubleadingPtExpSS")
hSubleadingPtOldSignal = fOldSignal.Get("SubleadingPtOS")
hSubleadingPtOldSignalExp = fOldSignal.Get("SubleadingPtExpSS")
hSubleadingPtNewLoose = fNewLoose.Get("SubleadingPtOS")
hSubleadingPtNewLooseExp = fNewLoose.Get("SubleadingPtExpSS")
hSubleadingPtNewSignal = fNewSignal.Get("SubleadingPtOS")
hSubleadingPtNewSignalExp = fNewSignal.Get("SubleadingPtExpSS")

hEtaOldLoose = fOldLoose.Get("EtaOS")
hEtaOldLooseExp = fOldLoose.Get("EtaExpSS")
hEtaOldSignal = fOldSignal.Get("EtaOS")
hEtaOldSignalExp = fOldSignal.Get("EtaExpSS")
hEtaNewLoose = fNewLoose.Get("EtaOS")
hEtaNewLooseExp = fNewLoose.Get("EtaExpSS")
hEtaNewSignal = fNewSignal.Get("EtaOS")
hEtaNewSignalExp = fNewSignal.Get("EtaExpSS")

hPhiOldLoose = fOldLoose.Get("PhiOS")
hPhiOldLooseExp = fOldLoose.Get("PhiExpSS")
hPhiOldSignal = fOldSignal.Get("PhiOS")
hPhiOldSignalExp = fOldSignal.Get("PhiExpSS")
hPhiNewLoose = fNewLoose.Get("PhiOS")
hPhiNewLooseExp = fNewLoose.Get("PhiExpSS")
hPhiNewSignal = fNewSignal.Get("PhiOS")
hPhiNewSignalExp = fNewSignal.Get("PhiExpSS")


hMassOldLoose.SetLineColor(ROOT.kRed)
hMassOldSignal.SetLineColor(ROOT.kRed)
hLeadingPtOldLoose.SetLineColor(ROOT.kRed)
hLeadingPtOldSignal.SetLineColor(ROOT.kRed)
hSubleadingPtOldLoose.SetLineColor(ROOT.kRed)
hSubleadingPtOldSignal.SetLineColor(ROOT.kRed)
hEtaOldLoose.SetLineColor(ROOT.kRed)
hEtaOldSignal.SetLineColor(ROOT.kRed)
hPhiOldLoose.SetLineColor(ROOT.kRed)
hPhiOldSignal.SetLineColor(ROOT.kRed)

##################

c = TCanvas()
c.Divide(1,2);
c.cd(1).SetPad(0, 0.25, 1, 1)
c.cd(1).SetLogy()
c.cd(2).SetPad(0, 0, 1, 0.25)
c.cd(2).SetGridy()

leg=TLegend(0.7, 0.8, 0.9, 0.9)
leg.AddEntry(hMassOldLoose, "20.1", "l")
leg.AddEntry(hMassNewLoose, "20.7", "l")



def setProps(hCompare):
	hCompare.SetTitle("")

	hCompareX =hCompare.GetXaxis()
	hCompareY = hCompare.GetYaxis()

	hCompareX.SetLabelOffset(999)
	hCompareX.SetLabelSize(0)
	hCompareX.SetTitle("")

	hCompareY.SetTitle("New/Old")
	hCompareY.SetTitleSize(0.1)
	hCompareY.SetTitleOffset(0.3)
	hCompareY.SetLabelSize(0.08)
	hCompareY.SetRangeUser(0.9,3)


c.Print("LooseComparisons.pdf[")

c.cd(1)
hMassOldLoose.Draw()
hMassNewLoose.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hMassNewLoose.Clone()
hCompare.Divide(hMassOldLoose)
setProps(hCompare)
hCompare.Draw()
c.Print("LooseComparisons.pdf", "Title:Mass")

c.cd(1)
hLeadingPtOldLoose.Draw()
hLeadingPtNewLoose.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hLeadingPtNewLoose.Clone()
hCompare.Divide(hLeadingPtOldLoose)
setProps(hCompare)
hCompare.Draw()
c.Print("LooseComparisons.pdf", "Title:LeadingPt")

c.cd(1)
hSubleadingPtOldLoose.Draw()
hSubleadingPtNewLoose.Draw("same")
leg.Draw() 
c.cd(2)
hCompare = hSubleadingPtNewLoose.Clone()
hCompare.Divide(hSubleadingPtOldLoose)
setProps(hCompare)
hCompare.Draw()
c.Print("LooseComparisons.pdf", "Title:SubleadingPt")

c.cd(1)
hEtaOldLoose.Draw()
hEtaNewLoose.Draw("same")
leg.Draw() 
c.cd(2)
hCompare = hEtaNewLoose.Clone()
hCompare.Divide(hEtaOldLoose)
setProps(hCompare)
hCompare.Draw()
c.Print("LooseComparisons.pdf", "Title:Eta")

c.cd(1)
hPhiOldLoose.Draw()
hPhiNewLoose.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hPhiNewLoose.Clone()
hCompare.Divide(hPhiOldLoose)
setProps(hCompare)
hCompare.Draw()
c.Print("LooseComparisons.pdf", "Title:Phi")
c.Print("LooseComparisons.pdf]")

###################

c.Print("SignalComparisons.pdf[")

c.cd(1)
hMassOldSignal.Draw()
hMassNewSignal.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hMassNewSignal.Clone()
hCompare.Divide(hMassOldSignal)
setProps(hCompare)
hCompare.Draw()
c.Print("SignalComparisons.pdf", "Title:Mass")

c.cd(1)
hLeadingPtOldSignal.Draw()
hLeadingPtNewSignal.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hLeadingPtNewSignal.Clone()
hCompare.Divide(hLeadingPtOldSignal)
setProps(hCompare)
hCompare.Draw()
c.Print("SignalComparisons.pdf", "Title:LeadingPt")

c.cd(1)
hSubleadingPtOldSignal.Draw()
hSubleadingPtNewSignal.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hSubleadingPtNewSignal.Clone()
hCompare.Divide(hSubleadingPtOldSignal)
setProps(hCompare)
hCompare.Draw()
c.Print("SignalComparisons.pdf", "Title:SubleadingPt")

c.cd(1)
hEtaOldSignal.Draw()
hEtaNewSignal.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hEtaNewSignal.Clone()
hCompare.Divide(hEtaOldSignal)
setProps(hCompare)
hCompare.Draw()
c.Print("SignalComparisons.pdf", "Title:Eta")

c.cd(1)
hPhiOldSignal.Draw()
hPhiNewSignal.Draw("same")
leg.Draw()
c.cd(2)
hCompare = hPhiNewSignal.Clone()
hCompare.Divide(hPhiOldSignal)
setProps(hCompare)
hCompare.Draw()
c.Print("SignalComparisons.pdf", "Title:Phi")
c.Print("SignalComparisons.pdf]")
